//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public Grade()
        {
            this.Student_GPA = new HashSet<Student_GPA>();
        }
    
        public int Id { get; set; }
        public string GradeScore { get; set; }
        public string GPA { get; set; }
    
        public virtual ICollection<Student_GPA> Student_GPA { get; set; }
    }
}
